function(DownloadTorch version cuda destination)
  if(NOT EXISTS ${destination}/libtorch)
    if(cuda)
      file(DOWNLOAD https://download.pytorch.org/libtorch/cu118/libtorch-win-shared-with-deps-${version}%2Bcu118.zip ${CMAKE_SOURCE_DIR}/torch.zip SHOW_PROGRESS)
      #file(DOWNLOAD https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-${version}%2Bcpu.zip ${CMAKE_CURRENT_SOURCE_DIR}/torch.zip SHOW_PROGRESS)
      message(STATUS "Extracting")
      file(ARCHIVE_EXTRACT INPUT ${CMAKE_SOURCE_DIR}/torch.zip DESTINATION ${destination})
      message(STATUS "Done Extracting")
      file(REMOVE ${CMAKE_SOURCE_DIR}/torch.zip)
    else()
      #file(DOWNLOAD https://download.pytorch.org/libtorch/cu118/libtorch-win-shared-with-deps-${version}%2Bcu118.zip ${CMAKE_CURRENT_SOURCE_DIR}/torch.zip SHOW_PROGRESS)
      file(DOWNLOAD https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-${version}%2Bcpu.zip ${CMAKE_SOURCE_DIR}/torch.zip SHOW_PROGRESS)
      message(STATUS "Extracting")
      file(ARCHIVE_EXTRACT INPUT ${CMAKE_SOURCE_DIR}/torch.zip DESTINATION ${destination})
      message(STATUS "Done Extracting")
      file(REMOVE ${CMAKE_SOURCE_DIR}/torch.zip)
    endif()
  endif()
endfunction()