name: Build OpenCV

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The opencv version to build"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - run: conda install -c conda-forge libjpeg-turbo libpng openjpeg
      - run: git clone --depth 1 --branch ${{ inputs.version }} https://github.com/opencv/opencv
      - run: mkdir build
      - run: mkdir built
      - run: cmake -DCMAKE_BUILD_TYPE=Release -S "./opencv/" -B "./build/"
      - run: cmake --build "./build" --config Release
      - run: cmake --install "./build" --prefix "./built"
      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'built.zip'
          path: 'built'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "opencv-win-${{inputs.version}}"
          title: "OpenCV ${{inputs.version}} Windows"
          files: |
            built.zip
        