name: Build OpenCV

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The opencv version to build"
        required: true
        type: string

jobs:
  build_binaries:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - run: conda install -c conda-forge libjpeg-turbo
      - run: conda install -c conda-forge libpng
      - run: git clone --depth 1 --branch ${{ inputs.version }} https://github.com/opencv/opencv
      - run: mkdir build
      - run: mkdir out
      - run: cmake -DCMAKE_BUILD_TYPE=Release -S "./opencv/" -B "./build/"
      - run: cmake --build "./build" --config Release
      - run: cmake --install "./build" --prefix "./out"
      - run: ls ./out
        